# Pipeline Configuration

data:
  raw_path: "data/raw/nlp_da.csv"
  processed_path: "data/processed/tickets_cleaned.csv"

chromadb:
  persist_directory: "data/chromadb"
  collection_name: "ticket_embeddings"

nlp:
  embedding_model: "sentence-transformers/all-MiniLM-L6-v2"

# Training part will be in model branch
model:
  name: "sentence-transformers/all-MiniLM-L6-v2"
  batch_size: 32
  epochs: 10
